resource_group_name    = "rg-db-workflows-cookbook"
location               = "UK South"
db_workspace_name      = "db-workspace-one"
db_workspace_name_sku  = "standard"
adls_gen2_account_name = "adlsgen2one"
storage_account_tier   = "Standard"