name: Terraform DB-Workflow Deploy
on:
  push:
    branches:
      - main
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@master
    - name: "Terraform Plan"
      uses: hashicorp/terraform-github-actions@master
      with: 
        tf_actions_version: latest
        tf_actions_subcommand: "plan"
        tf_actions_working_dir: "./terraform"
        tf_actions_comment: true
        tf_actions_init_args: "-backend-config=./terraform/environment_definition.tfvars"
    - name: "Terraform Init"
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: latest
        tf_actions_subcommand: "init"
        tf_actions_working_dir: "./terraform"
        tf_actions_comment: true
    - name: "Terraform Validate"
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: latest
        tf_actions_subcommand: "validate"
        tf_actions_working_dir: "./terraform"
        tf_actions_comment: true
    - name: "Terraform Plan"
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: latest
        tf_actions_subcommand: "plan"
        tf_actions_working_dir: "./terraform"
        tf_actions_comment: true
      env:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
    - name: "Terraform Apply"
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.13
        tf_actions_subcommand: "apply"
        tf_actions_working_dir: "./terraform"
        tf_actions_comment: true
      env:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'