name: Terraform DB-Workflow Deploy
on:
  push:
    branches:
      - main
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - run: echo "The name of the branch is ${{ github.ref }} and repository is ${{ github.repository }}."
    - name: Checkout Repository
      uses: actions/checkout@master
    - name: Format Terraform files
      run: terraform fmt -check=true -recursive ./terraform
      working-directory: "./terraform"
    - name: Terraform Format
      uses: hashicorp/terraform-github-actions@master
      with: 
        tf_actions_version: 1.8.0
        tf_actions_subcommand: "fmt"
        tf_actions_working_dir: "./terraform"
        tf_actions_comment: true
    - name: Terraform Init
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.8.0
        tf_actions_subcommand: "init"
        tf_actions_working_dir: "./terraform"
        tf_actions_comment: true
    - name: Terraform Validate
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.8.0
        tf_actions_subcommand: "validate"
        tf_actions_working_dir: "./terraform"
        tf_actions_comment: true
    - name: Terraform Plan
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.8.0
        tf_actions_subcommand: "plan"
        tf_actions_working_dir: "./terraform"
        tf_actions_comment: true
      env:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
    - name: Terraform Apply
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.8.0
        tf_actions_subcommand: "apply"
        tf_actions_working_dir: "./terraform"
        tf_actions_comment: true
      env:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'