name: Terraform DB-Workflow Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        path: main

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Set up Azure CLI
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          # Add your Azure CLI commands here
          # For example:
          az login --service-principal -u ${{fromJson(secrets.AZURE_CREDENTIALS).clientId}} -p ${{fromJson(secrets.AZURE_CREDENTIALS).clientSecret}} --tenant ${{fromJson(secrets.AZURE_CREDENTIALS).tenantId}}
      
    - name: Decode Azure Credentials
      run: echo "${{ secrets.AZURE_CREDENTIALS }}" > azure_creds.json

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -var-file=./scripts/environment_definition.tfvars

    - name: Terraform Apply
      run: terraform apply -auto-approve -var-file=./scripts/environment_definition.tfvars
      env:
        ARM_CLIENT_ID: ${{fromJson(secrets.AZURE_CREDENTIALS).clientId}}
        ARM_CLIENT_SECRET: ${{fromJson(secrets.AZURE_CREDENTIALS).clientSecret}}
        ARM_SUBSCRIPTION_ID: ${{fromJson(secrets.AZURE_CREDENTIALS).subscriptionId}}
        ARM_TENANT_ID: ${{fromJson(secrets.AZURE_CREDENTIALS).tenantId}}
